name: CI

on:
  push:
  pull_request:

env:
  CARGO_INCREMENTAL: 0

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly, 1.62.1]

    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install ${{ matrix.rust }} --profile minimal
      - run: cargo +${{ matrix.rust }} test

  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install stable --profile minimal --component rustfmt,clippy
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets
      - run: cargo doc --no-deps
