name: CI

permissions:
  contents: read

on:
  push:
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1
  CI: 1

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable, beta, nightly, 1.62.1]

    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install ${{ matrix.rust }} --profile minimal
      - run: cargo +${{ matrix.rust }} test

  lint:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v6
      - run: rustup toolchain install stable --profile minimal --component rustfmt,clippy
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets
      - run: cargo doc --no-deps

  semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Check semver
        uses: obi1kenobi/cargo-semver-checks-action@v2
