//! Git binary diffs support.
//!
//! This module provides parsing and decoding for Git's binary diff format,
//! as generated by `git diff --binary` or `git format-patch --binary`.
//!
//! Based on [DiffX Binary Diffs specification](https://diffx.org/spec/binary-diffs.html).

#[cfg(feature = "binary")]
mod base85;
#[cfg(feature = "binary")]
mod delta;

use std::{fmt, ops::Range};

/// The type of a binary patch block.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinaryBlockKind {
    /// [Literal](https://diffx.org/spec/binary-diffs.html#git-literal-binary-diffs):
    /// contains the full file content, zlib-compressed and Base85-encoded.
    Literal,
    /// [Delta](https://diffx.org/spec/binary-diffs.html#git-delta-binary-diffs):
    /// contains delta instructions to transform one file into another.
    Delta,
}

/// A single block in a binary patch.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BinaryBlock<'a> {
    /// The type of this block (literal content or delta instructions).
    pub kind: BinaryBlockKind,
    /// The encoded data.
    pub data: BinaryData<'a>,
}

/// A parsed binary patch.
///
/// A binary patch contains encoded binary data that can be decoded
/// to recover the original and modified file contents.
///
/// Git may use different encodings for each direction:
///
/// - `literal`: full file content
/// - `delta`: instructions to transform one file into another
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BinaryPatch<'a> {
    /// A full binary patch with forward and reverse data.
    ///
    /// The forward block transforms original -> modified.
    /// The reverse block transforms modified -> original.
    ///
    /// Each block can independently be either `literal` or `delta`.
    Full {
        /// Forward transformation (original -> modified).
        forward: BinaryBlock<'a>,
        /// Reverse transformation (modified -> original).
        reverse: BinaryBlock<'a>,
    },
    /// A Git binary diff marker.
    ///
    /// This represents the `Binary files a/path and b/path differ` case,
    /// where git detected a binary change but didn't include the actual data.
    ///
    /// Calling [`apply()`](Self::apply) on this variant returns an error.
    Marker,
}

impl<'a> BinaryPatch<'a> {
    /// Applies a binary patch forward: original -> modified.
    ///
    /// - If the forward block is `Literal`: returns the decoded content directly.
    /// - If the forward block is `Delta`: applies delta instructions to `original`.
    ///
    /// Unlike `git apply`, this doesn't validate the original content hash.
    #[cfg(feature = "binary")]
    pub fn apply(&self, original: &[u8]) -> Result<Vec<u8>, BinaryPatchParseError> {
        match self {
            BinaryPatch::Full { forward, .. } => Self::apply_block(forward, original),
            BinaryPatch::Marker => Err(BinaryPatchParseErrorKind::NoBinaryData.into()),
        }
    }

    /// Applies a binary patch in reverse: modified -> original.
    ///
    /// - If the reverse block is `Literal`: returns the decoded content directly.
    /// - If the reverse block is `Delta`: applies delta instructions to `modified`.
    ///
    /// Unlike `git apply`, this doesn't validate the modified content hash.
    #[cfg(feature = "binary")]
    pub fn apply_reverse(&self, modified: &[u8]) -> Result<Vec<u8>, BinaryPatchParseError> {
        match self {
            BinaryPatch::Full { reverse, .. } => Self::apply_block(reverse, modified),
            BinaryPatch::Marker => Err(BinaryPatchParseErrorKind::NoBinaryData.into()),
        }
    }

    /// Applies a single block (either literal or delta).
    #[cfg(feature = "binary")]
    fn apply_block(block: &BinaryBlock<'_>, base: &[u8]) -> Result<Vec<u8>, BinaryPatchParseError> {
        match block.kind {
            BinaryBlockKind::Literal => Self::decode_data(&block.data),
            BinaryBlockKind::Delta => {
                let delta_instructions = Self::decode_data(&block.data)?;
                delta::apply(base, &delta_instructions).map_err(BinaryPatchParseError::from)
            }
        }
    }

    /// See [Decoding Logic](https://diffx.org/spec/binary-diffs.html#decoding-logic)
    #[cfg(feature = "binary")]
    fn decode_data(binary_data: &BinaryData<'_>) -> Result<Vec<u8>, BinaryPatchParseError> {
        use std::io::Read;

        let compressed = decode_base85_lines(binary_data.data)?;

        let mut decoder = flate2::read::ZlibDecoder::new(&compressed[..]);
        let mut decompressed = Vec::new();
        decoder
            .read_to_end(&mut decompressed)
            .map_err(|e| BinaryPatchParseErrorKind::DecompressionFailed(e.to_string()))?;

        Ok(decompressed)
    }
}

/// Represents a single binary payload in a Git binary diff.
///
/// For example, the following patch block
///
/// * is parsed as `BinaryData { size: 10, data: "UcmV+l0QLU>0RjUA1qKHQ2>\`DEE&u=k" }`
/// * The line starts with a length indicator (`U` = 21 decoded bytes)
///
///
/// ```text
/// literal 10
/// UcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BinaryData<'a> {
    /// Uncompressed size in bytes.
    pub size: u64,
    /// Raw Base85 lines with length indicators.
    pub data: &'a str,
}

/// Error type for binary patch operations.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BinaryPatchParseError {
    pub(crate) kind: BinaryPatchParseErrorKind,
    span: Option<Range<usize>>,
}

impl BinaryPatchParseError {
    /// Creates a new error with the given kind and span.
    pub(crate) fn new(kind: BinaryPatchParseErrorKind, span: Range<usize>) -> Self {
        Self {
            kind,
            span: Some(span),
        }
    }

    /// Returns the byte range in the input where the error occurred.
    pub fn span(&self) -> Option<Range<usize>> {
        self.span.clone()
    }
}

impl fmt::Display for BinaryPatchParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if let Some(span) = &self.span {
            write!(
                f,
                "error parsing binary patch at byte {}: {}",
                span.start, self.kind
            )
        } else {
            write!(f, "error parsing binary patch: {}", self.kind)
        }
    }
}

impl std::error::Error for BinaryPatchParseError {}

#[cfg(feature = "binary")]
impl From<base85::Base85Error> for BinaryPatchParseError {
    fn from(e: base85::Base85Error) -> Self {
        BinaryPatchParseErrorKind::Base85(e).into()
    }
}

#[cfg(feature = "binary")]
impl From<delta::DeltaError> for BinaryPatchParseError {
    fn from(e: delta::DeltaError) -> Self {
        BinaryPatchParseErrorKind::Delta(e).into()
    }
}

impl From<BinaryPatchParseErrorKind> for BinaryPatchParseError {
    fn from(kind: BinaryPatchParseErrorKind) -> Self {
        Self { kind, span: None }
    }
}

/// The kind of error that occurred when parsing a binary patch.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(crate) enum BinaryPatchParseErrorKind {
    /// Missing or invalid "GIT binary patch" header.
    // TODO: Switch to #[expect(dead_code)] when MSRV >= 1.81
    #[cfg_attr(not(feature = "binary"), allow(dead_code))]
    InvalidHeader,

    /// First binary block (forward) not found.
    MissingForwardBlock,

    /// Second binary block (reverse) not found.
    MissingReverseBlock,

    /// No binary data available (marker-only patch).
    // TODO: Switch to #[expect(dead_code)] when MSRV >= 1.81
    #[cfg_attr(not(feature = "binary"), allow(dead_code))]
    NoBinaryData,

    /// Invalid line length indicator in Base85 data.
    // TODO: Switch to #[expect(dead_code)] when MSRV >= 1.81
    #[cfg_attr(not(feature = "binary"), allow(dead_code))]
    InvalidLineLengthIndicator,

    /// Base85 decoding failed.
    #[cfg(feature = "binary")]
    Base85(base85::Base85Error),

    /// Delta application failed.
    #[cfg(feature = "binary")]
    Delta(delta::DeltaError),

    /// Zlib decompression failed.
    #[cfg(feature = "binary")]
    DecompressionFailed(String),
}

impl fmt::Display for BinaryPatchParseErrorKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidHeader => write!(f, "invalid binary patch header"),
            Self::MissingForwardBlock => write!(f, "first binary block not found"),
            Self::MissingReverseBlock => write!(f, "second binary block not found"),
            Self::NoBinaryData => write!(f, "no binary data available"),
            Self::InvalidLineLengthIndicator => write!(f, "invalid line length indicator"),
            #[cfg(feature = "binary")]
            Self::Base85(e) => write!(f, "{e}"),
            #[cfg(feature = "binary")]
            Self::Delta(e) => write!(f, "{e}"),
            #[cfg(feature = "binary")]
            Self::DecompressionFailed(msg) => write!(f, "decompression failed: {msg}"),
        }
    }
}

/// Simple streaming parser for binary patches using lines() iterator.
struct BinaryParser<'a> {
    input: &'a str,
    offset: usize,
}

impl<'a> BinaryParser<'a> {
    fn new(input: &'a str) -> Self {
        Self { input, offset: 0 }
    }

    fn peek_line(&self) -> Option<&'a str> {
        self.input[self.offset..].lines().next()
    }

    /// Creates an error with the current offset as span.
    fn error(&self, kind: BinaryPatchParseErrorKind) -> BinaryPatchParseError {
        BinaryPatchParseError::new(kind, self.offset..self.offset)
    }

    fn next_line(&mut self) -> Option<&'a str> {
        let rest = &self.input[self.offset..];
        let line = rest.lines().next()?;
        self.offset += line.len();

        // Skip line ending (CRLF or LF)
        let remaining = &self.input[self.offset..];
        if remaining.starts_with("\r\n") {
            self.offset += 2;
        } else if remaining.starts_with('\n') {
            self.offset += 1;
        }

        Some(line)
    }

    fn slice_from(&self, start_offset: usize) -> &'a str {
        let end = self.offset;
        // Strip trailing line ending before blank line
        let slice = &self.input[start_offset..end];
        slice
            .strip_suffix("\r\n")
            .or_else(|| slice.strip_suffix('\n'))
            .unwrap_or(slice)
    }
}

/// Parses binary patch content after git extended headers.
///
/// Expects input starting with "GIT binary patch" line.
/// Returns the parsed patch and the number of bytes consumed.
///
/// Format:
///
/// ```text
/// GIT binary patch
/// <literal|delta> <modified_size>
/// <base85_lines>
///
/// <literal|delta> <original_size>
/// <base85_lines>
/// ```
pub(crate) fn parse_binary_patch(
    input: &str,
) -> Result<(BinaryPatch<'_>, usize), BinaryPatchParseError> {
    let mut parser = BinaryParser::new(input);

    // Expect "GIT binary patch" marker
    if parser.next_line() != Some("GIT binary patch") {
        return Err(parser.error(BinaryPatchParseErrorKind::InvalidHeader));
    }

    // Parse first block (forward: original -> modified)
    let Some(forward) = parse_binary_block(&mut parser) else {
        return Err(parser.error(BinaryPatchParseErrorKind::MissingForwardBlock));
    };

    // Parse second block (reverse: modified -> original)
    let Some(reverse) = parse_binary_block(&mut parser) else {
        return Err(parser.error(BinaryPatchParseErrorKind::MissingReverseBlock));
    };

    Ok((BinaryPatch::Full { forward, reverse }, parser.offset))
}

/// Parses a single binary block.
///
/// Returns a `BinaryBlock` with kind (literal/delta) and data.
fn parse_binary_block<'a>(parser: &mut BinaryParser<'a>) -> Option<BinaryBlock<'a>> {
    // Parse "literal 10" or "delta 18"
    let format_line = parser.next_line()?;
    let (patch_type, size_str) = format_line.split_once(' ')?;
    let size: u64 = size_str.parse().ok()?;

    let kind = match patch_type {
        "literal" => BinaryBlockKind::Literal,
        "delta" => BinaryBlockKind::Delta,
        _ => return None,
    };

    // Record start of Base85 data
    let data_start = parser.offset;

    // Consume Base85 lines until blank line
    while let Some(line) = parser.peek_line() {
        if line.is_empty() {
            parser.next_line(); // Consume blank line
            break;
        }
        parser.next_line();
    }

    let data = parser.slice_from(data_start);

    Some(BinaryBlock {
        kind,
        data: BinaryData { size, data },
    })
}

/// Decodes multi-line Base85 data with length indicators.
///
/// Each line has the format: `<len_c><data>`
///
/// From [5.1.1. Binary Payloads](https://diffx.org/spec/binary-diffs.html#binary-payloads):
///
/// > Each line represents up to 52 bytes of pre-encoded data.
/// > There may be an unlimited number of lines.
/// > They contain the following fields:
/// >
/// >  * `len_c` is a line length character.
/// >     This encodes the length of the (pre-encoded) data written on this line.
/// >  * `data` is Base85-encoded data for this line.
#[cfg(feature = "binary")]
fn decode_base85_lines(data: &str) -> Result<Vec<u8>, BinaryPatchParseError> {
    // A rough estimate: In Base85, 5 chars -> 4 bytes
    let mut result = Vec::with_capacity(data.len() * 4 / 5);

    for line in data.lines() {
        if line.is_empty() {
            continue;
        }

        let line_bytes = line.as_bytes();

        let length = decode_line_length(line_bytes[0])
            .ok_or(BinaryPatchParseErrorKind::InvalidLineLengthIndicator)?;
        let encoded = &line[1..];
        let start = result.len();
        base85::decode_into(encoded, &mut result)?;
        result.truncate(start + length);
    }

    Ok(result)
}

/// Decodes a line length character to its numeric value.
///
/// From [Line Length Characters](https://diffx.org/spec/binary-diffs.html#line-length-characters):
///
/// > Each encoded line in a binary diff payload is prefixed by a line length character.
/// > This encodes the length of the compressed (but not encoded) data for the line.
/// >
/// > Line length characters always represent a value between 1 and 52:
/// >
/// > * A value of A-Z represents a number between 1..26.
/// > * A value of a-z represents a number between 27..52.
#[cfg(feature = "binary")]
fn decode_line_length(c: u8) -> Option<usize> {
    match c {
        b'A'..=b'Z' => Some((c - b'A' + 1) as usize),
        b'a'..=b'z' => Some((c - b'a' + 27) as usize),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_literal_format_simple() {
        let input = "GIT binary patch\nliteral 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\nliteral 0\nKcmV+b0RR6000031\n\n";
        let (patch, consumed) = parse_binary_patch(input).unwrap();

        assert_eq!(consumed, input.len());
        match &patch {
            BinaryPatch::Full { forward, reverse } => {
                assert_eq!(forward.kind, BinaryBlockKind::Literal);
                assert_eq!(forward.data.size, 10);
                assert_eq!(reverse.kind, BinaryBlockKind::Literal);
                assert_eq!(reverse.data.size, 0);
            }
            _ => panic!("expected Full variant"),
        }
    }

    #[test]
    fn parse_delta_format() {
        let input = "GIT binary patch\ndelta 18\nccmV+t0PX*P2!IH%^Z^9`00000v-trB0x!=5aR2}S\n\ndelta 18\nccmV+t0PX*P2!IH%^Z^BFm9#}av-trB0zxAOrvLx|\n\n";
        let (patch, _) = parse_binary_patch(input).unwrap();

        match &patch {
            BinaryPatch::Full { forward, reverse } => {
                assert_eq!(forward.kind, BinaryBlockKind::Delta);
                assert_eq!(forward.data.size, 18);
                assert_eq!(reverse.kind, BinaryBlockKind::Delta);
                assert_eq!(reverse.data.size, 18);
            }
            _ => panic!("expected Full variant"),
        }
    }

    #[test]
    fn parse_invalid_header() {
        // Without "GIT binary patch" marker, parse_binary_patch returns error
        let input = "literal 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\n";
        let err = parse_binary_patch(input).unwrap_err();
        assert_eq!(err.kind, BinaryPatchParseErrorKind::InvalidHeader);
    }

    #[test]
    fn parse_with_crlf_line_endings() {
        let input = "GIT binary patch\r\nliteral 10\r\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\r\n\r\nliteral 0\r\nKcmV+b0RR6000031\r\n\r\n";
        let (patch, consumed) = parse_binary_patch(input).unwrap();

        assert_eq!(consumed, input.len());
        match &patch {
            BinaryPatch::Full { forward, reverse } => {
                assert_eq!(forward.kind, BinaryBlockKind::Literal);
                assert_eq!(forward.data.size, 10);
                assert_eq!(reverse.kind, BinaryBlockKind::Literal);
                assert_eq!(reverse.data.size, 0);
            }
            _ => panic!("expected Full variant"),
        }
    }

    #[test]
    fn parse_mixed_format() {
        // Git can use different encoding for each direction
        let input = "GIT binary patch\nliteral 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\ndelta 18\nccmV+t0PX*P2!IH%^Z^9`00000v-trB0x!=5aR2}S\n\n";
        let (patch, _) = parse_binary_patch(input).unwrap();

        match &patch {
            BinaryPatch::Full { forward, reverse } => {
                assert_eq!(forward.kind, BinaryBlockKind::Literal);
                assert_eq!(reverse.kind, BinaryBlockKind::Delta);
            }
            _ => panic!("expected Full variant"),
        }
    }
}

#[cfg(test)]
#[cfg(feature = "binary")]
mod apply_tests {
    use super::*;

    #[test]
    fn decode_line_length_uppercase() {
        assert_eq!(decode_line_length(b'A'), Some(1));
        assert_eq!(decode_line_length(b'B'), Some(2));
        assert_eq!(decode_line_length(b'Z'), Some(26));
    }

    #[test]
    fn decode_line_length_lowercase() {
        assert_eq!(decode_line_length(b'a'), Some(27));
        assert_eq!(decode_line_length(b'b'), Some(28));
        assert_eq!(decode_line_length(b'z'), Some(52));
    }

    #[test]
    fn decode_line_length_invalid() {
        assert_eq!(decode_line_length(b'0'), None);
        assert_eq!(decode_line_length(b'!'), None);
        assert_eq!(decode_line_length(b' '), None);
    }

    #[test]
    fn apply_literal_patch() {
        let input = "GIT binary patch\nliteral 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\nliteral 0\nKcmV+b0RR6000031\n\n";
        let (patch, _) = parse_binary_patch(input).unwrap();

        let modified = patch.apply(&[]).unwrap();
        assert_eq!(modified.len(), 10);
        assert_eq!(modified, vec![0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);

        let original = patch.apply_reverse(&[]).unwrap();
        assert_eq!(original.len(), 0);
    }

    #[test]
    fn apply_with_crlf_line_endings() {
        let input = "GIT binary patch\r\nliteral 10\r\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\r\n\r\nliteral 0\r\nKcmV+b0RR6000031\r\n\r\n";
        let (patch, _) = parse_binary_patch(input).unwrap();

        let modified = patch.apply(&[]).unwrap();
        assert_eq!(modified, vec![0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
        let original = patch.apply_reverse(&[]).unwrap();
        assert_eq!(original.len(), 0);
    }
}
