//! Git binary diffs support.
//!
//! This module provides parsing and decoding for Git's binary diff format,
//! as generated by `git diff --binary` or `git format-patch --binary`.
//!
//! Based on [DiffX Binary Diffs specification](https://diffx.org/spec/binary-diffs.html).

use std::{fmt, ops::Range};

/// The type of a binary patch block.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BinaryBlockKind {
    /// [Literal](https://diffx.org/spec/binary-diffs.html#git-literal-binary-diffs):
    /// contains the full file content, zlib-compressed and Base85-encoded.
    Literal,
    /// [Delta](https://diffx.org/spec/binary-diffs.html#git-delta-binary-diffs):
    /// contains delta instructions to transform one file into another.
    Delta,
}

/// A single block in a binary patch.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BinaryBlock<'a> {
    /// The type of this block (literal content or delta instructions).
    pub kind: BinaryBlockKind,
    /// The encoded data.
    pub data: BinaryData<'a>,
}

/// A parsed binary patch.
///
/// A binary patch contains encoded binary data that can be decoded
/// to recover the original and modified file contents.
///
/// Git may use different encodings for each direction:
///
/// - `literal`: full file content
/// - `delta`: instructions to transform one file into another
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum BinaryPatch<'a> {
    /// A full binary patch with forward and reverse data.
    ///
    /// The forward block transforms original -> modified.
    /// The reverse block transforms modified -> original.
    ///
    /// Each block can independently be either `literal` or `delta`.
    Full {
        /// Forward transformation (original -> modified).
        forward: BinaryBlock<'a>,
        /// Reverse transformation (modified -> original).
        reverse: BinaryBlock<'a>,
    },
    /// A Git binary diff marker.
    ///
    /// This represents the `Binary files a/path and b/path differ` case,
    /// where git detected a binary change but didn't include the actual data.
    Marker,
}

/// Represents a single binary payload in a Git binary diff.
///
/// For example, the following patch block
///
/// * is parsed as `BinaryData { size: 10, data: "UcmV+l0QLU>0RjUA1qKHQ2>\`DEE&u=k" }`
/// * The line starts with a length indicator (`U` = 21 decoded bytes)
///
///
/// ```text
/// literal 10
/// UcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BinaryData<'a> {
    /// Uncompressed size in bytes.
    pub size: u64,
    /// Raw Base85 lines with length indicators.
    pub data: &'a str,
}

/// Error type for binary patch operations.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BinaryPatchParseError {
    pub(crate) kind: BinaryPatchParseErrorKind,
    span: Option<Range<usize>>,
}

impl BinaryPatchParseError {
    /// Creates a new error with the given kind and span.
    pub(crate) fn new(kind: BinaryPatchParseErrorKind, span: Range<usize>) -> Self {
        Self {
            kind,
            span: Some(span),
        }
    }

    /// Returns the byte range in the input where the error occurred.
    pub fn span(&self) -> Option<Range<usize>> {
        self.span.clone()
    }
}

impl fmt::Display for BinaryPatchParseError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if let Some(span) = &self.span {
            write!(
                f,
                "error parsing binary patch at byte {}: {}",
                span.start, self.kind
            )
        } else {
            write!(f, "error parsing binary patch: {}", self.kind)
        }
    }
}

impl std::error::Error for BinaryPatchParseError {}

impl From<BinaryPatchParseErrorKind> for BinaryPatchParseError {
    fn from(kind: BinaryPatchParseErrorKind) -> Self {
        Self { kind, span: None }
    }
}

/// The kind of error that occurred when parsing a binary patch.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub(crate) enum BinaryPatchParseErrorKind {
    /// Missing or invalid "GIT binary patch" header.
    InvalidHeader,

    /// First binary block (forward) not found.
    MissingForwardBlock,

    /// Second binary block (reverse) not found.
    MissingReverseBlock,

    /// No binary data available (marker-only patch).
    NoBinaryData,

    /// Invalid line length indicator in Base85 data.
    InvalidLineLengthIndicator,
}

impl fmt::Display for BinaryPatchParseErrorKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidHeader => write!(f, "invalid binary patch header"),
            Self::MissingForwardBlock => write!(f, "first binary block not found"),
            Self::MissingReverseBlock => write!(f, "second binary block not found"),
            Self::NoBinaryData => write!(f, "no binary data available"),
            Self::InvalidLineLengthIndicator => write!(f, "invalid line length indicator"),
        }
    }
}

/// Simple streaming parser for binary patches.
struct BinaryParser<'a> {
    input: &'a str,
    offset: usize,
}

impl<'a> BinaryParser<'a> {
    fn new(input: &'a str) -> Self {
        Self { input, offset: 0 }
    }

    /// Creates an error with the current offset as span.
    fn error(&self, kind: BinaryPatchParseErrorKind) -> BinaryPatchParseError {
        BinaryPatchParseError::new(kind, self.offset..self.offset)
    }

    fn next_line(&mut self) -> Option<&'a str> {
        let rest = &self.input[self.offset..];
        if rest.is_empty() {
            return None;
        }
        let (line, skip) = match rest.find('\n') {
            Some(pos) => (&rest[..pos], pos + 1),
            None => (rest, rest.len()),
        };
        self.offset += skip;
        Some(line.strip_suffix('\r').unwrap_or(line))
    }
}

/// Parses binary patch content after git extended headers.
///
/// Expects input starting with "GIT binary patch" line.
/// Returns the parsed patch and the number of bytes consumed.
///
/// Format:
///
/// ```text
/// GIT binary patch
/// <literal|delta> <modified_size>
/// <base85_lines>
///
/// <literal|delta> <original_size>
/// <base85_lines>
/// ```
pub(crate) fn parse_binary_patch(
    input: &str,
) -> Result<(BinaryPatch<'_>, usize), BinaryPatchParseError> {
    let mut parser = BinaryParser::new(input);

    // Expect "GIT binary patch" marker
    if parser.next_line() != Some("GIT binary patch") {
        return Err(parser.error(BinaryPatchParseErrorKind::InvalidHeader));
    }

    // Parse first block (forward: original -> modified)
    let Some(forward) = parse_binary_block(&mut parser) else {
        return Err(parser.error(BinaryPatchParseErrorKind::MissingForwardBlock));
    };

    // Parse second block (reverse: modified -> original)
    let Some(reverse) = parse_binary_block(&mut parser) else {
        return Err(parser.error(BinaryPatchParseErrorKind::MissingReverseBlock));
    };

    Ok((BinaryPatch::Full { forward, reverse }, parser.offset))
}

/// Parses a single binary block.
///
/// Returns a `BinaryBlock` with kind (literal/delta) and data.
fn parse_binary_block<'a>(parser: &mut BinaryParser<'a>) -> Option<BinaryBlock<'a>> {
    // Parse "literal 10" or "delta 18"
    let format_line = parser.next_line()?;
    let (patch_type, size_str) = format_line.split_once(' ')?;
    let size: u64 = size_str.parse().ok()?;

    let kind = match patch_type {
        "literal" => BinaryBlockKind::Literal,
        "delta" => BinaryBlockKind::Delta,
        _ => return None,
    };

    // Consume Base85 lines until blank line, tracking the end of actual data.
    let data_start = parser.offset;
    let mut data_end = data_start;
    while let Some(line) = parser.next_line() {
        if line.is_empty() {
            break;
        }
        data_end = parser.offset;
    }

    // Slice the data lines, stripping the final line ending.
    let data = &parser.input[data_start..data_end];
    let data = data
        .strip_suffix("\r\n")
        .or_else(|| data.strip_suffix('\n'))
        .unwrap_or(data);

    Some(BinaryBlock {
        kind,
        data: BinaryData { size, data },
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_literal_format_simple() {
        let input = "GIT binary patch\nliteral 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\nliteral 0\nKcmV+b0RR6000031\n\n";
        let (patch, consumed) = parse_binary_patch(input).unwrap();

        assert_eq!(consumed, input.len());
        match &patch {
            BinaryPatch::Full { forward, reverse } => {
                assert_eq!(forward.kind, BinaryBlockKind::Literal);
                assert_eq!(forward.data.size, 10);
                assert_eq!(reverse.kind, BinaryBlockKind::Literal);
                assert_eq!(reverse.data.size, 0);
            }
            _ => panic!("expected Full variant"),
        }
    }

    #[test]
    fn parse_delta_format() {
        let input = "GIT binary patch\ndelta 18\nccmV+t0PX*P2!IH%^Z^9`00000v-trB0x!=5aR2}S\n\ndelta 18\nccmV+t0PX*P2!IH%^Z^BFm9#}av-trB0zxAOrvLx|\n\n";
        let (patch, _) = parse_binary_patch(input).unwrap();

        match &patch {
            BinaryPatch::Full { forward, reverse } => {
                assert_eq!(forward.kind, BinaryBlockKind::Delta);
                assert_eq!(forward.data.size, 18);
                assert_eq!(reverse.kind, BinaryBlockKind::Delta);
                assert_eq!(reverse.data.size, 18);
            }
            _ => panic!("expected Full variant"),
        }
    }

    #[test]
    fn parse_invalid_header() {
        // Without "GIT binary patch" marker, parse_binary_patch returns error
        let input = "literal 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\n";
        let err = parse_binary_patch(input).unwrap_err();
        assert_eq!(err.kind, BinaryPatchParseErrorKind::InvalidHeader);
    }

    #[test]
    fn parse_with_crlf_line_endings() {
        let input = "GIT binary patch\r\nliteral 10\r\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\r\n\r\nliteral 0\r\nKcmV+b0RR6000031\r\n\r\n";
        let (patch, consumed) = parse_binary_patch(input).unwrap();

        assert_eq!(consumed, input.len());
        match &patch {
            BinaryPatch::Full { forward, reverse } => {
                assert_eq!(forward.kind, BinaryBlockKind::Literal);
                assert_eq!(forward.data.size, 10);
                assert_eq!(reverse.kind, BinaryBlockKind::Literal);
                assert_eq!(reverse.data.size, 0);
            }
            _ => panic!("expected Full variant"),
        }
    }

    #[test]
    fn parse_mixed_format() {
        // Git can use different encoding for each direction
        let input = "GIT binary patch\nliteral 10\nUcmV+l0QLU>0RjUA1qKHQ2>`DEE&u=k\n\ndelta 18\nccmV+t0PX*P2!IH%^Z^9`00000v-trB0x!=5aR2}S\n\n";
        let (patch, _) = parse_binary_patch(input).unwrap();

        match &patch {
            BinaryPatch::Full { forward, reverse } => {
                assert_eq!(forward.kind, BinaryBlockKind::Literal);
                assert_eq!(reverse.kind, BinaryBlockKind::Delta);
            }
            _ => panic!("expected Full variant"),
        }
    }
}
